language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: waxee6tbuOBqeQHZHbKEOrC3CUGZJJR/zA70VlMX38waTDTASNOBGPnyzDdoCRLGDebwvT0agnquKfjp5vJxShz0qrNVwMYQLzBQbMLHkzDt4GrmdzhzOyJGFvhMg3ka5sYOxG0P4ES3eOS/AnIF+cgWvFN5nIkQQuIPrrkPsjpeZcJcDx/IxSPje0alUyh4qtsRItOmxZP3rlRmqJbomt/BB9LG+ZXcuf0Iw+GyQj1d+tdyz6/mUpMkDylRo8P6BDMzIFuDN3BecixGjGw1G8aEaM/qoAvVJsDyEDF8CsPkaOmnCjw5CJmA904Vud9fuSnjzYJesns4/biqt8dmcJN6/6aqpY/qf5ij5AGauUdV67zhW3Gf0X0JNZopEQsXRni2a86rvE6G2vPtkNXmOW+/1W6U912GFPiuEtuVLLWfsrRmFBVX21OE0epqEFm++p4UnnQu/6Iondm7clR9ANqUIYLvn82PHpCGSboaWsaCuR64mpmGhT4n25MwsOqR+C060KiapeVhByvXeXVcVZ8guhyQgcEFcfwMpLC8NP2Uzuio7a0tHsZnrXO894UASYtkP1asOaGc43CqvM2Ernkf32ygKa2SWk5KgIGT7DoTNBfY59MK7/7oBc1SmiA4KIm95bNqyabbs0Ddy8wEPzATYEkFklCSeSfNaEoQer4=
  app: afternoon-caverns-98233
  on:
    repo: afterburnerDS/restaurant-mongoose-tests
    branch: feature/with-tests
