language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: qc/LdX3UtjZfkcZNbWfzMCF56+bXVQcnAyM9m3aJG5EjGkdlBLY54cV/fgE9mqIRmQYBiBZvDR97qwlDYKRgIEzdw9Ixhy+m1B59cy3cFzgVZzxnCofLjQcsqGMnRtvwjong2jgYVkzjLxFQ0YLZeJY6QUD93ShXFixTVl1tV/XYXJsA+WnJrYPQXRVyO2UWkoAP9GgUUeDLUWPtS78GesGxvshyy8V3v8JrSpZS71uv2nlqV6k1vqQbu65WfNpguyNr0kHWy7QRzGrHf0+IbnboPRr4VgEaoGYM0bCBvPij1nLNRR3CB8JVjR+B2R4e3aSCaGf9UoyFKrDKlc+z4F/2ZGE1k1M0e7K6k6PoaNfFuBtf7ntyWe9oNPxLEXVran3PdwqCXLPKx4Vuyzj8/k4amDe+oB5muM28scCNxqL3yphRZWu5VYQp6qeE5AD2FOcinArwSgkIkivM3hDHCRBBYbRKIpDSX1fJHMjgHSyneJ5S54Z3/28xPbA/nLPWtkrfSf67T9PVmfdTdx7Zc5UFAbFCBmGwEt0QS2KdrST0qS88Rt9Ojc1XGpIhkGA9Pe3co/1bmOCi8d1iitW0nD14n5FiO4yWdpxohKK8HgfLGnSiVJLsiQD60SzhaN2ZcXBi3fBa+lpy2LJmiQxkwfoghoiBiwR1dRxjZmkYEac=
  app: afternoon-caverns-98233
  on:
    repo: afterburnerDS/restaurant-mongoose-tests
    branch: feature/with-tests
